# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='dataType',
            field=models.CharField(default=0, max_length=32, verbose_name='数据类型, 0 :股票 1: 期货'),
            preserve_default=False,
        ),
    ]
