# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byx', '0002_data_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='upTime',
            field=models.DateTimeField(auto_now=True, verbose_name='数据更新时间'),
        ),
    ]
