# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byx', '0004_auto_20170619_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dataType',
            field=models.IntegerField(verbose_name='数据类型, 0 :股票 >1: 期货'),
        ),
    ]
