# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byx', '0005_auto_20170620_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='tj',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='上行类别名称'),
        ),
        migrations.AlterField(
            model_name='tj',
            name='type',
            field=models.IntegerField(verbose_name='上行类别'),
        ),
    ]
